name: Build and push images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r service1/requirements.txt

      - name: Run Service1 tests
        working-directory: ./service1
        run: |
          pytest tests/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push service1 image
        uses: docker/build-push-action@v5
        with:
          context: ./service1
          push: true
          tags: asifkhan131/service1:latest

      - name: Build and push service2 image
        uses: docker/build-push-action@v5
        with:
          context: ./service2
          push: true
          tags: asifkhan131/service2:latest
          
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: api_avengers
          key: ${{ secrets.AZURE_VM_KEY }}
          script: |
            docker pull asifkhan131/service1:latest
            docker pull asifkhan131/service2:latest
            docker compose down
            docker compose up -d


  
